export const skills = [
  {
    name: "Languages",
    items: ["JavaScript", "TypeScript"],
  },
  {
    name: "Frontend",
    items: ["Tailwind CSS", "React.js", "Next.js", "Redux"],
  },
  {
    name: "Backend",
    items: [
      "Node.js",
      "Express.js",
      "Nest.js",
      "BullMQ",
      "TypeORM",
      "WebSocket",
    ],
  },
  {
    name: "Database",
    items: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
  },
  {
    name: "AI",
    items: ["MCP", "Ollama", "AI Automation", "API Integrations"],
  },
  {
    name: "DevOps & Tools",
    items: [
      "Git",
      "GitHub",
      "Docker",
      "Docker Compose",
      "Caddy",
      "NGINX",
      "CI/CD",
      "GitHub Actions",
      "Railway",
      "Linux",
      "Postman",
      "Chrome Dev Tools",
      "VSCode",
      "Cursor",
      "Antigravity",
    ],
  },
  {
    name: "Other",
    items: [
      "Multi-tenant Architecture",
      "Event-Driven Design",
      "RESTful API Design",
      "RBAC",
      "OOP",
      "Zod",
      "i18n (EN/FR)",
      "Agile",
      "OpenAI / AI APIs",
      "React Native",
      "Python",
    ],
  },
];
